# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2020-07-03 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_teacher_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_formal',
            field=models.BooleanField(default=True, verbose_name='\u6b63\u5f0f'),
        ),
    ]
