# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2020-08-03 18:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_student_is_formal'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='major',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes', related_query_name='class', to='school.Major', verbose_name='\u4e13\u4e1a'),
        ),
    ]
