# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2020-08-07 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20200615_1913'),
        ('school', '0004_class_major'),
    ]

    operations = [
        migrations.AddField(
            model_name='major',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='school_majors', to='course.Course', verbose_name='\u8bfe\u7a0b'),
        ),
    ]
