# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2020-12-10 01:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_major_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='\u6807\u7b7e'),
        ),
    ]
